services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    environment:
      - ORACLE_SID=xe
      - ORACLE_PWD=Shafana77
    ports:
      - 1522:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup   
volumes:
  oracle-data:
  oracle-backup:	
